// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"gin-hello-world/internal/handler"
	"gin-hello-world/internal/service"
	"github.com/google/wire"
)

// Injectors from wire.go:

// InitializeHandlers 初始化所有 handlers
func InitializeHandlers() (*Handlers, error) {
	workerService := service.NewWorkerService()
	helloService := service.NewHelloService(workerService)
	helloHandler := handler.NewHelloHandler(helloService)
	workerHandler := handler.NewWorkerHandler(workerService)
	snowflakeHandler := handler.NewSnowflakeHandler()
	handlers := &Handlers{
		HelloHandler:     helloHandler,
		WorkerHandler:    workerHandler,
		SnowflakeHandler: snowflakeHandler,
	}
	return handlers, nil
}

// wire.go:

// Handlers 聚合所有 handler
type Handlers struct {
	HelloHandler     *handler.HelloHandler
	WorkerHandler    *handler.WorkerHandler
	SnowflakeHandler *handler.SnowflakeHandler
}

// ServiceSet 定义 service 层的 providers
var ServiceSet = wire.NewSet(service.NewHelloService, service.NewWorkerService)

// HandlerSet 定义 handler 层的 providers
var HandlerSet = wire.NewSet(handler.NewHelloHandler, handler.NewWorkerHandler, handler.NewSnowflakeHandler)
